import { existsSync } from 'node:fs'
import { join, resolve } from 'node:path'
import getDeepMergeFunction from '@fastify/deepmerge'
import { ensure, read, write } from './ioutils.cjs'

/**
 * This is the Vite plugin, not the Fastify plugin.
 *
 * Writes the vite.config properties used by fastify-vite to a JSON file in the node_modules/.cache
 * directory so production builds do not need to import vite nor the actual vite.config  file. This
 * allows vite to remain a devDependency and not need to exist on production Docker images.
 *
 * @returns
 */
export function viteFastify() {
  let jsonFilePath
  let configToWrite = {}
  let resolvedConfig = {}

  return {
    name: 'vite-fastify',
    async config(config) {
      const deepMerge = getDeepMergeFunction()
      const {
        resolveClientModule,
        createSSREnvironment,
        createClientEnvironment,
      } = await import('./config.js')

      config.environments = {}
      config.environments.client = deepMerge(
        createClientEnvironment(),
        config.environments.client ?? {},
      )
      const clientModule = resolveClientModule(config.root)
      config.environments.ssr = deepMerge(
        createSSREnvironment(clientModule),
        config.environments.ssr ?? {},
      )
    },
    async configResolved(config = {}) {
      const { base, build, isProduction, root } = config
      const { assetsDir } = build || {}

      // During vite dev builds, this function can be called multiple times. Sometimes, the resolved
      // configs in these executions are missing many properties. Since there is no advantage to
      // running this function during dev, we save build time and prevent errors by returning early.
      if (!isProduction) {
        return
      }

      resolvedConfig = config

      // For SSR builds, `vite build` is executed twice: once for client and once for server.
      // We need to merge the two configs and make both `outDir` properties available.
      const fastify = {
        outDirs: {},
      }
      fastify.entryPaths = Object.fromEntries(
        Object.entries(resolvedConfig.environments)
          .map(([env, envConfig]) => {
            if (envConfig.build.outDir) {
              fastify.outDirs[env] = envConfig.build.outDir
            }
            if (envConfig.build?.rollupOptions?.input?.index) {
              return [env, envConfig.build?.rollupOptions?.input?.index]
            }
            return false
          })
          .filter(Boolean),
      )

      configToWrite = {
        base,
        root,
        build: {
          assetsDir,
          outDir: fastify.outDirs.client ?? 'dist/client',
        },
        // Special key that does not exist on Vite's ResolvedConfig type for properties that only
        // belong to this plugin. Also serves as an indicator to FastifyVite that this config was
        // generated by this plugin and is not the dev vite instance.
        fastify: {},
      }

      jsonFilePath = join(
        root,
        findCommonPath(Object.values(fastify.outDirs)),
        'config.json',
      )

      if (existsSync(jsonFilePath)) {
        const existingJson = JSON.parse(await read(jsonFilePath, 'utf-8'))
        if (existingJson.fastify) {
          configToWrite.fastify = {
            ...existingJson.fastify,
            ...fastify,
          }
        }
      }
    },

    // Write the JSON file after the bundle finishes writing to avoid getting deleted by emptyOutDir
    async writeBundle() {
      if (resolvedConfig.isProduction) {
        await write(
          jsonFilePath,
          JSON.stringify(configToWrite, undefined, 2),
          'utf-8',
        )
      }
    },
  }
}

function findCommonPath(paths) {
  if (paths.length === 1) {
    return paths[0]
  }
  const segments = paths.map((path) => path.split('/'))
  const minLength = Math.min(...segments.map((arr) => arr.length))
  const commonSegments = []
  for (let i = 0; i < minLength; i++) {
    const segment = segments[0][i]
    if (segments.every((arr) => arr[i] === segment)) {
      commonSegments.push(segment)
    } else {
      break
    }
  }

  return commonSegments.join('/')
}

export default viteFastify
