packages:
  - docs/
  - packages/**
  - examples/*
  - starters/*

catalog:
  '@fastify/middie': ^9.1.0
  devalue: ^5.6.2
  fastify: ^5.7.4
  html-rewriter-wasm: ^0.4.1
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.3.1
  vitest: ^4.0.18

catalogs:
  eslint:
    '@eslint/js': ^9.39.2
    eslint: ^9.39.2
    eslint-config-prettier: ^10.1.8
    eslint-plugin-vue: ^10.6.2
    globals: ^16.5.0
    typescript-eslint: ^8.51.0
    vue-eslint-parser: ^10.2.0
  react:
    '@vitejs/plugin-react': ^5.1.3
    react: ^19.2.4
    react-dom: ^19.2.4
    react-router: ^7.12.0
  solid:
    solid-js: ^1.9.5
  vue:
    '@vitejs/plugin-vue': ^6.0.3
    vue: ^3.5.26
    vue-router: ^4.6.4
