packages:
  - "docs/"
  - "packages/**"
  - "examples/**"
  - "contrib/**"
  - "starters/**"

catalog:
  devalue: ^5.1.1
  fastify: ^5.2.2
  react: ^19.1.0
  react-dom: ^19.1.0
  solid-js: ^1.9.5
  vite: ^6.2.4
  vue: ^3.5.13
  vue-router: ^4.5.0
  '@vitejs/plugin-vue': ^5.2.3