packages:
  - docs/
  - packages/**
  - examples/*
  - starters/*

catalog:
  '@fastify/middie': ^9.3.1
  devalue: ^5.7.1
  fastify: ^5.8.4
  tsx: ^4.21.0
  typescript: ^6.0.2
  vite: ^8.0.7
  vitest: ^4.1.2

catalogs:
  eslint:
    '@eslint/js': ^10.0.1
    eslint: ^10.2.0
    eslint-config-prettier: ^10.1.8
    eslint-plugin-vue: ^10.8.0
    globals: ^17.4.0
    typescript-eslint: ^8.58.1
    vue-eslint-parser: ^10.4.0
  react:
    '@vitejs/plugin-react': ^6.0.1
    react: ^19.2.4
    react-dom: ^19.2.4
    react-router: ^7.12.0
  solid:
    solid-js: ^1.9.5
  vue:
    '@vitejs/plugin-vue': ^6.0.5
    vue: ^3.5.26
    vue-router: ^4.6.4
