parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  ecmaVersion: 2021
  sourceType: module
  babelOptions:
    presets:
      - solid
  ecmaFeatures:
    jsx: true
extends:
  - plugin:solid/recommended
  - standard
plugins:
  - solid
rules:
  import/no-absolute-path: off
