parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true
extends:
  - plugin:svelte/recommended
  - standard
plugins:
  - svelte
rules:
  import/no-absolute-path: off
