parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true
extends:
  - plugin:vue/vue3-recommended
  - standard
plugins:
  - vue
rules:
  import/no-absolute-path: off
  vue/multi-word-component-names: off
  vue/html-closing-bracket-newline: off
