name: E2E

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  examples:
    name: examples (${{ matrix.node-version }})
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        node-version: [22.x, 24.x, 25.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: 'pnpm'
          check-latest: true
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Build @fastify/vite
        run: pnpm --filter @fastify/vite build

      - name: Run E2E tests
        run: pnpm test:e2e
